name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # checkout
      # install docker-ce # install docker-compose
      # pull code and run docker compose to build
      # export TEST SETTINGS and run test
      #
  #stage_env:

  #prod_env:

  #publish:
  #deploy: